# CazaEstilo/admin/config.yml

backend:
  # Usamos 'git-gateway' porque ya activaste Netlify Identity/Git Gateway
  name: git-gateway 
  # *** REEMPLAZA CON TU USUARIO/REPOSITORIO EXACTO ***
  repo: CazaEstilo/CazaEstilo 
  branch: main # O 'master', según la rama principal de tu repositorio

# Configuraciones de Medios
# Asegúrate de crear esta carpeta en la raíz: assets/img/products/
media_folder: "assets/img/products" 
public_folder: "/assets/img/products" 

# Define la estructura de los productos (Colección 'Productos')
collections:
  - name: "productos" 
    label: "Productos Destacados" 
    # Asegúrate de crear esta carpeta en la raíz: _productos/
    folder: "_productos" 
    create: true 
    slug: "{{slug}}"
    format: "json" 
    fields: 
      - {label: "Nombre del Producto", name: "title", widget: "string"}
      # Usamos 'markdown' para permitir descripciones más largas y con formato
      - {label: "Descripción Detallada", name: "body", widget: "markdown", required: true}
      - {label: "Precio (COP)", name: "price", widget: "number", value_type: "int", min: 0, step: 100}
      - {label: "Stock Disponible (0 = Agotado)", name: "stock", widget: "number", value_type: "int", min: 0, default: 1}
      - {label: "Calidad (%)", name: "quality", widget: "number", value_type: "int", min: 0, max: 100, default: 100}
      - {label: "Imágenes del Carrusel (Max 3)", name: "images", widget: "list", fields:
          - {label: "Imagen", name: "image", widget: "image", choose_url: false, allow_multiple: false}
        , max: 3, min: 1, required: true}