# Archivo: admin/config.yml (CÓDIGO MODIFICADO)

backend:
  # Usamos 'git-gateway' porque activaste Netlify Identity/Git Gateway
  name: git-gateway 
  # *** ESTA ES LA RUTA EXACTA DE TU REPOSITORIO ***
  repo: cazaestilo/CazaEstilo 
  branch: main # o 'master'

# CONFIGURACIÓN DE RUTA BASE (¡ESTO SOLUCIONA EL PROBLEMA!)
# Netlify usa esto para saber dónde está la raíz real de tu sitio
site_url: https://cazaestilo.github.io/CazaEstilo
base_url: https://cazaestilo.github.io/CazaEstilo 

# Configuraciones de Medios
media_folder: "assets/img/products" 
public_folder: "/assets/img/products" 

# Define la estructura de los productos
collections:
  - name: "productos" 
    label: "Productos Destacados" 
    folder: "_productos" 
    create: true 
    slug: "{{slug}}"
    format: "json" 
    fields: 
      - {label: "Nombre del Producto", name: "title", widget: "string"}
      - {label: "Descripción Detallada", name: "body", widget: "markdown", required: true}
      - {label: "Precio (COP)", name: "price", widget: "number", value_type: "int", min: 0, step: 100}
      - {label: "Stock Disponible (0 = Agotado)", name: "stock", widget: "number", value_type: "int", min: 0, default: 1}
      - {label: "Calidad (%)", name: "quality", widget: "number", value_type: "int", min: 0, max: 100, default: 100}
      - {label: "Imágenes del Carrusel (Max 3)", name: "images", widget: "list", fields:
          - {label: "Imagen", name: "image", widget: "image", choose_url: false, allow_multiple: false}
        , max: 3, min: 1, required: true}