backend:
  # USAR EL NUEVO NOMBRE DEL REPOSITORIO
  name: github                                    
  repo: cazaestilo/cazaestilo.github.io           
  branch: main
  
# RUTAS DE PUBLICACIÓN EN LA RAÍZ (Las más simples posibles)
base_url: /  
site_url: https://cazaestilo.github.io/ 

# RUTAS DE MEDIOS (sin subdirectorio)
media_folder: "assets/img/products" 
public_folder: "/assets/img/products" 

# DEFINICIÓN DE COLECCIONES (AJUSTAR ESTO SI ES NECESARIO)
collections:
  - name: "productos"
    label: "Productos Destacados"
    folder: "_productos"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Nombre del Producto", name: "title", widget: "string"}
      - {label: "Descripción Detallada", name: "body", widget: "markdown"}
      - {label: "Precio (COP)", name: "price", widget: "number"}
      - {label: "Stock Disponible", name: "stock", widget: "number"}
      - {label: "Calidad (%)", name: "quality", widget: "number"}
      - label: "Imágenes del Carrusel"
        name: "images"
        widget: "list"
        fields:
          - {label: "Imagen", name: "image", widget: "image"}